### ISSUE TITLE
Güncelleme

### ISSUE THREAD

**Issue by ghost** [oxcakmak/PHP---Login-instagram-using-php-and-curl#2]
Merhabalar, projeniz şuanda çalışmamaktadır. Günceller misiniz?

**Comment by oxcakmak** [comment]
Check: https://github.com/oxcakmak/PHP---Login-instagram-using-php-and-curl/issues/1

**Comment by ghost** [comment]
> Check: #1

Denedim fakat çalışmamakta.

**Comment by oxcakmak** [comment]
> > Check: #1
> 
> Denedim fakat çalışmamakta.

Ne hatası alıyorsun php kısmında?

**Comment by ghost** [comment]
> > > Check: #1
> > 
> > 
> > Denedim fakat çalışmamakta.
> 
> Ne hatası alıyorsun php kısmında?

Hata vermiyor fakat login olmuyor.

**Comment by farukclk** [comment]
hocam soruna cozum bulabıldınız mı?

**Comment by oxcakmak** [comment]
> hocam soruna cozum bulabıldınız mı?

anydesk ile incelemek gerek. Websitesindeki numaradan iletişime geç.

**Comment by ramo25** [comment]
Is not working. Do not login .. Possibly a problem in sending the password post field

**Comment by oxcakmak** [comment]
Change login form to:
if (!preg_match('/<form data-encrypt method="POST" id="login-form" class="adjacent".*?<\/form>/is', $page, $form)) {
