### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by vspok** [oxcakmak/PHP---Login-instagram-using-php-and-curl#4]
Still works?

**Comment by oxcakmak** [comment]
yes, working.

**Comment by MTHS1901** [comment]
its not works because instagram disabled  "?force_classic_login"

**Comment by MTHS1901** [comment]
can you update it to works using "https://www.instagram.com/accounts/login/?force_authentication=1"

**Comment by oxcakmak** [comment]
> can you update it to works using "https://www.instagram.com/accounts/login/?force_authentication=1"

Thanks for the help, I'll update of course
